### ISSUE TITLE
Where is the Russian language?

### ISSUE THREAD

**Issue by alekssamos** [rhasspy/piper#66] opened 2023-05-05 13:53 UTC
There is Ukrainian, but there is no Russian. Will this language appear in the future?

**Comment by Shulyaka** [comment] 2023-05-07 19:57
Possibly a duplicate of #51

**Comment by synesthesiam** [comment] 2023-05-08 21:20
The [previous Russian voices I trained for Mimic 3](https://mycroftai.github.io/mimic3-voices/#ru_RU) did not receive very positive feedback, so I'm looking for volunteers.

@alekssamos Please drop me a line at voice@nabucasa.com if you're interested in contributing your voice (or know someone who is).

**Comment by synesthesiam** [comment] 2023-05-11 15:52
I was able to get a copy of the "Irina" dataset for training. Here are some samples from it training overnight: https://drive.google.com/drive/folders/1YZFYnfT4SJ20k7_RRnLKrtfHFmFJ_T_5?usp=share_link

Any major pronunciation errors you can hear? Or any suggested test sentences?

**Comment by alexmorbo** [comment] 2023-05-12 19:32
@synesthesiam 
1.wav, 2.wav, 3.wav - very fine
0.wav - bad emphasis in 1 word
4.wav - bad emphasis in 1 word
5.wav - bad emphasis in 1 word, bad pronunciation in last word

**Comment by synesthesiam** [comment] 2023-05-12 20:16
Thanks @alexmorbo, can you specify which words have bad emphasis? This is probably just a fix needed in the espeak dictionary.

**Comment by alexmorbo** [comment] 2023-05-12 20:26
> Thanks @alexmorbo, can you specify which words have bad emphasis? This is probably just a fix needed in the espeak dictionary.

Yeah, I listening now again, and what i see:

0.wav - `радУга` - incorrect, `рАдуга` - correct
4.wav - `разъЯренный` - incorrect, `разъярЁнный` - correct, i think error with letter "ё" 
4.wav - `пЯтью` - incorrect, `пятьЮ` - correct
4.wav - `жердЯми` - incorrect, `жЕрдями` - correct
5.wav - `В чащах` - wrong pronunciation, i saw to txt, to find what is it.  `экземпляр` - same

**Comment by Shulyaka** [comment] 2023-05-15 21:17
Okay, I am not a linguist, but as far as I understand the problem here is that many languages (including English) have no inherent rules for which syllable should be stressed. Hence, the neural network can't learn that without being fed with an entire dictionary recorded by someone.
May I suggest an improvement? I think we need two neural networks working in sequence. The first will annotate the text with stress marks, and the second one will generate the sound.
The benefit is that we don't need a human to read it all out to train the first network.
And we also don't need to rerecord the all the existing samples - just annotate the dataset an retrain it.
In the future we may add some more annotations like suggested intonation or character.
Also would be good at this stage to convert all numbers into text.

**Comment by vzenrhen** [comment] 2023-05-16 12:48
Thank you @synesthesiam for your work.

Is it possible to specify accent explicitly? For example, a special character like `

**Comment by Shulyaka** [comment] 2023-06-01 23:12
> 4.wav - `жердЯми` - incorrect, `жЕрдями` - correct

Actually I've found a reference that `жердЯми` is correct.
https://где-ударение.рф/%D0%B2-%D1%81%D0%BB%D0%BE%D0%B2%D0%B5-%D0%B6%D0%B5%D1%80%D0%B4%D1%8F%D0%BC%D0%B8/

**Comment by synesthesiam** [comment] 2023-06-21 21:32
It seems like we need to train a separate model to add accents to Russian text, like [ukrainian-accentor](https://github.com/egorsmkv/ukrainian-accentor).

**Closed** 2023-11-14 22:11 UTC
